version: '3.9'

services:
  backend:
    build:
      context: ./translatorV1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./translatorV1:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./translatorFE
      dockerfile: dockerfile.dev
    command: npm run dev -- --host 0.0.0.0 --port 3000
    volumes:
      - ./translatorFE:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  frontend.prod:
    build:
      context: ./translatorFE
      dockerfile: dockerfile.prod
    volumes:
      - ./translatorFE:/app
    ports:
      - "80:80"